# Generated by Django 4.1.4 on 2023-01-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_stops_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
